Test: update program tests
anitab-org/bridge-in-tech-backend pull request #137
Opened 2020-09-14 20:00 UTC by KapilBansal320

### Description

Added test cases for update program (PUT /organizations/{organization_id}/programs/{program_id} api endpoint

Fixes #128 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

- run `python -m unittest discover tests` to see all tests passed

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-09-14 20:02 UTC, KapilBansal320 commented
@mtreacy002 Please review this pull request too. Also review #136 before this one.

2020-09-15 02:11 UTC, mtreacy002 requested changes
@KapilBansal320 , can you please check my feedback below? I've mentioned few things that need to be addressed. Thanks

2020-09-15 02:11 UTC, mtreacy002 commented on tests/programs/test_api_update_program.py
> +class ProgramBaseTestCase(BaseTestCase):
@KapilBansal320 . Be careful of the naming of the class. This shouldn't be named ProgramBaseTestCase since this class is about testing update program api. It's a good practice to maintain consistency in the naming style used in the previous tests. You can see the naming style from the screenshot below and rename this class accordingly.

<img width="343" alt="Screen Shot 2020-09-15 at 11 24 52 am" src="https://user-images.githubusercontent.com/29667122/93154098-23495000-f746-11ea-86a2-279352ea3689.png">

2020-09-15 02:11 UTC, mtreacy002 commented on tests/programs/test_api_update_program.py
> +        self.update_payload_program = {
Since the purpose is to check if the update is successful, you should try use one or two different values from the program details that already exist in the database. From the existing program you injected to the database (line 129) and the payload here, it doesn't seems like details being changed.

2020-09-15 02:11 UTC, mtreacy002 commented on tests/programs/test_api_update_program.py
> +        self.organization_id = 3
Here you don't need to use self. since this constant is specific only to this block of test.

2020-09-15 02:11 UTC, mtreacy002 commented on tests/programs/test_api_update_program.py
> +        response = self.client.put(
The logic in this test a bit off. As part of the Program logic, the user need to declare they represent organization first before they can create an organization then create a program. This means to create an organization and program they must alrady have user_extension instance in the database (You can see in your test setup() that the organization is using user1 id as the representative). So, this test block (user is not the rep of organization so is not allowed to update program), although resulted in pass, this is not something that will ever happen in the actual application.

Other way to test this point is to create another organization and another program in this block of test and use that organization and program to test if user1 can send this update program request. Also, with this logic, you can move the user1 user_extension initiation (line 164 and 186) to the setup() block.

2020-09-15 11:17 UTC, KapilBansal320 commented
@mtreacy002 I have made the necessary change. Review it once more. Thanks

2020-09-16 04:23 UTC, mtreacy002 approved these changes
Well done, @KapilBansal320 for addressing all requested changes. I'm approving this 👍.

2020-09-20 12:45 UTC, merged