Fix: Replace token access expiry to further future date
anitab-org/bridge-in-tech-backend pull request #167
Opened 2020-10-03 00:40 UTC by mtreacy002

### Description
Replace the token access expiry to future date (Oct 2, 2021) so the tests won't fail.

Fixes #165 

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Runniing tests on VSCode IDE Tests explorer and on terminal resulted in all tests passed.
<img width="1680" alt="Screen Shot 2020-10-03 at 10 20 09 am" src="https://user-images.githubusercontent.com/29667122/94979178-b1a23c00-0564-11eb-846c-22530ee4a1a2.png">

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2020-10-03 07:58 UTC, vj-codes submitted a review, later dismissed
LGTM 🎉 
@mtreacy002 so until next year , there won't be any update needed right?

2020-10-03 07:59 UTC, vj-codes commented
Can I add the `needs review` label ?

2020-10-03 22:42 UTC, mtreacy002 commented
> LGTM 🎉
> @mtreacy002 so until next year , there won't be any update needed right?

Yep, you are right, @vj-codes  ...😁😁😁

2020-10-03 23:45 UTC, devkapilbansal commented
Where the token is actually updated?? I am able to locate it in success messages only. :eyes:

2020-10-04 00:15 UTC, mtreacy002 commented
> Where the token is actually updated?? I am able to locate it in success messages only. 👀

@devkapilbansal , have you tried pulling this PR and run it locally? This is the preferred method to test if the fiix actually works or not.

2020-10-04 00:25 UTC, mtreacy002 commented
> Where the token is actually updated?? I am able to locate it in success messages only. 👀

This success message that gets returrned when user login is used by the app to set Authorization cookie "access_expiry". 
<img width="729" alt="Screen Shot 2020-10-04 at 11 18 13 am" src="https://user-images.githubusercontent.com/29667122/95004232-3f992800-0634-11eb-983c-4f8b71bf7888.png">


The reason why the tests were failing before was because on each API requests we have token validation check which one of its purpose is to check if the token is still valid by looking into this Authorization cookie. 
<img width="718" alt="Screen Shot 2020-10-04 at 11 21 48 am" src="https://user-images.githubusercontent.com/29667122/95004211-0cef2f80-0634-11eb-915a-065a686d864b.png">

Thus, making sure that mock login api call return a valid access_expiry date will fix this bug.

2020-10-04 09:45 UTC, devkapilbansal approved these changes, later dismissed
Works fine for me

2020-10-04 09:46 UTC, isabelcosta requested changes
@mtreacy002 instead of changing the timestamp to real specific times, you can use time() or datetime() functions to get a specific time within a specific interval. Here's an example of mentorship-backend project https://github.com/anitab-org/mentorship-backend/blob/80114acd59/tests/users/test_dao.py#L165

In this way, your test won't have to be changed periodically :)

2020-10-13 23:02 UTC, mtreacy002 commented
@isabelcosta, @devkapilbansal and @vj-codes , I've pushed the requested changes. Now all tests will self-adjust on time related fields so there'll be no need to keep extending time when it is set to specific time. Can you please re-review? Thanks

2020-10-14 11:28 UTC, devkapilbansal reviewed
@mtreacy002 do we need to add a success message in each file. Instead, can't we declare it at one place and used in other places. Like in messages directory itself.
Although, it works fine for me locally. :+1:

2020-10-14 21:05 UTC, mtreacy002 commented
> @mtreacy002 do we need to add a success message in each file. Instead, can't we declare it at one place and used in other places. Like in messages directory itself.
> Although, it works fine for me locally. 👍

@devkapilbansal , the reason why I didn't put this in the base test as part of test setup is because the register tests and one of the login tests do not need the user to login. Hope this makes sense

2020-10-15 18:33 UTC, devkapilbansal approved these changes
Thanks for the explanation

2020-10-24 23:17 UTC, isabelcosta approved these changes
💪 @mtreacy002 👏

2020-10-24 23:18 UTC, merged