Update Python version in README #213
anitab-org/bridge-in-tech-backend pull request #217
Opened 2021-03-14 15:54 UTC by dcs-soni

### Description

Updated the Python version in Readme to Python 3.7

Fixes #213 

### Type of Change:
-Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2021-03-18 03:43 UTC, HeroicHitesh requested changes

2021-03-18 03:43 UTC, HeroicHitesh commented on README.md
> +[![Python 3.7](https://img.shields.io/badge/python-3.x-blue.svg)](https://www.python.org/downloads/)
@dcs-soni Can you please change Python Version in the Badge link also so that it will be visible correctly.

2021-03-18 04:59 UTC, HeroicHitesh approved these changes
LGTM👍
@dcs-soni Thanks for your contribution 🎉

2021-03-20 02:49 UTC, mtreacy002 approved these changes
Well done, @dcs-soni for your fix and thanks for contributing to the project 🎉🎉🎉. Will approve and merge this now as no test needed (only relates to documentation).

2021-03-20 02:50 UTC, merged