229 update contributing
anitab-org/bridge-in-tech-backend pull request #259
Opened 2021-04-07 13:45 UTC by y-martinez

### Description

- Add the Zulip project stream link
- Improve the text changing connectors and punctuation marks

![Final result](https://user-images.githubusercontent.com/6761059/113875726-109b7480-9785-11eb-89b2-a7be863449d8.png)

Fixes #229 

### Type of Change:

- Documentation

### How Has This Been Tested?

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

2021-04-08 20:41 UTC, devkapilbansal requested changes
@y-martinez LGTM
Just a minor suggestion here

2021-04-08 20:41 UTC, devkapilbansal commented on .github/CONTRIBUTING.md
> +* Have a short description of what has gone wrong (like a root cause analysis and description of the fix), if that information is not already present in the issue.
```suggestion
* Give a short description of what went wrong (like a root cause analysis and description of the fix), if that information is not already present in the issue.
```

2021-04-08 20:44 UTC, devkapilbansal approved these changes
Thanks for the changes.
LGTM :+1:

2021-04-09 03:38 UTC, epicadk approved these changes
Looks good

2021-04-09 04:24 UTC, decon-harsh approved these changes

2021-04-09 04:24 UTC, decon-harsh commented
LGTM Nice work

2021-04-09 05:08 UTC, HeroicHitesh approved these changes
LGTM

2021-04-09 17:40 UTC, codesankalp approved these changes
LGTM :rocket:

2021-04-09 23:59 UTC, mtreacy002 approved these changes
Well done, @y-martinez for your fix and thank you for contributing to the project 🎉🎉🎉

2021-04-09 23:59 UTC, merged