test : Manual testing POST /register
anitab-org/bridge-in-tech-backend pull request #285
Opened 2021-05-29 21:22 UTC by Aryamanz29

### Description

- Perform manual testing and report `POST /register API`
-  Added Test Report  Markdown `.\docs\manual_tests\test_register.md`

Fixes #235

### Type of Change:

- Testing
- Documentation

### How Has This Been Tested?

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

2021-05-29 21:30 UTC, devkapilbansal commented
@Aryamanz29 ensure all test cases are covered and please use link to the image instead of adding images in the repository.

For this you can upload your images in comment copy the URL and use there

2021-05-31 17:38 UTC, Aryamanz29 commented
@devkapilbansal  Update : 
- Added some more tests.
- Removed test ss directory.
-  One more thing I've noticed while testing that a new user created when I filling an email field like `xyz@xyz.com123`, See this is an invalid email address, but we get a positive result, instead of getting `400 BAD REQUEST` 

![Screenshot (171)](https://user-images.githubusercontent.com/56113566/120226598-24cf8f80-c265-11eb-98ef-30e930103c88.png)

![Screenshot (172)](https://user-images.githubusercontent.com/56113566/120226603-26995300-c265-11eb-8f6b-1dd4880d83d4.png)

2021-06-09 03:21 UTC, mtreacy002 requested changes
@Aryamanz29 , thank you for your work on the issue. I suggest that you can have the tests put under the following structure:
* Test Description: /register [method = POST]
    * Positive tests
        * subsections.... 
     * Negative tests 
        * subsections.... 

Hope this makes sense 😉

2021-06-09 03:21 UTC, mtreacy002 commented on docs/manual_tests/test_register.md
> +- **Expected Result** : A new user should be created.
Since you've shown 3 different examples (this and the following 2 tests) of when a new user should be created based on the combinations of `need mentoring` and `available to mentor` attributes, you can put these 3 under the `Positive tests` section.

2021-06-09 03:21 UTC, mtreacy002 commented on docs/manual_tests/test_register.md
> +- **Expected Result** : A new user shouldn't be created.
This and the following tests can be put under the `Negative tests` section then give each tests subtitle based on the type of test being done, e.g. `If username already exist, etc`.

2021-06-23 01:10 UTC, mtreacy002 commented
@aryaman, can we please get an update on this?

2021-06-23 07:00 UTC, Aryamanz29 commented
> @Aryaman, can we please get an update on this?

Sorry @mtreacy002  I forgot about this PR 😅,  Done requested changes ✔, Ready for review ✌

2021-07-09 00:28 UTC, mtreacy002 approved these changes
@Aryamanz29 , this looks good to me now 👍.
Thank you for your contribution to the project 🎉🎉🎉. Since this is a documentation pr, no testing is needed. Will approve and merge this now 😉.

2021-07-09 00:29 UTC, merged