docs: update README file
anitab-org/bridge-in-tech-backend pull request #3
Opened 2020-05-09 03:38 UTC by Menina294

### Description

Made suggested changes to README file.

Fixes #1 and replaced PR#2

### Type of Change:

- Documentation

### How Has This Been Tested?

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] I have made corresponding changes to the documentation

2020-05-10 23:43 UTC, mtreacy002 commented
Perfect... Congratulations, Diana... You have managed to fix your develop branch 🎉 🥳 💃

2020-05-10 23:48 UTC, Menina294 commented
Woo🎉! Glad that my develop branch is working now!

2020-05-10 23:51 UTC, mtreacy002 commented
You're awesome, @Menina294. Thank you for your resilience and commitment you've shown on your first contribution to AnitaB open source. 💖

2020-05-11 00:10 UTC, mtreacy002 commented
I'll soon give my review on this PR. I'll let you know when I'm done 😉 .

2020-05-11 00:26 UTC, Menina294 commented
Aww, thanks so much for helping me along the way @mtreacy002 and @isabelcosta 💖! I always felt intimidated by reaching out (especially in the backend repos), but I'm really glad that you two were able to help me along the way 😊. I'll absolutely try my best to contribute to bridge-in-tech backend and maybe learn a thing or two along the way.

Also I hope you two don't have to deal with too many gramatic errors because I'm prone to those 😅😂.

2020-05-11 00:34 UTC, mtreacy002 commented
> Aww, thanks so much for helping me along the way @mtreacy002 and @isabelcosta 💖! I always felt intimidated by reaching out (especially in the backend repos), but I'm really glad that you two were able to help me along the way 😊. I'll absolutely try my best to contribute to bridge-in-tech backend and maybe learn a thing or two along the way.
> 
> Also I hope you two don't have to deal with too many gramatic errors because I'm prone to those 😅😂.

You're most welcomed, @Menina294. Look forward to work together with you in our journey ahead 😉. Don't worry about grammar. I'm a bit slack in that area (rarely double check what I wrote and just post comments in a rush and quite often to late to realise that I made grammar errors). 😂 😊

2020-05-11 01:05 UTC, mtreacy002 requested changes
I just requested a little change here. Other than that, it looks find to me, @Menina294.

2020-05-11 01:05 UTC, mtreacy002 commented on .github/README.md
> +Bridge-In-Tech is an application that allows industries/companies, mentors and students to actively collaborate to one another.
I think you forgot this part where @isabelcosta [requested in the previous PR](https://github.com/anitab-org/bridge-in-tech-backend/pull/2#discussion_r421863271) this description of the project (line 8 & 10) should be placed directly under the page title (line1). So can you move it to line 3, @Menina294?

2020-05-11 01:49 UTC, Menina294 commented on .github/README.md
> +Bridge-In-Tech is an application that allows industries/companies, mentors and students to actively collaborate to one another.
Shoot, I thought I added that one! I'll make sure to include it.

2020-05-11 01:59 UTC, Menina294 commented
Just to make sure, once I commited it, I click on "Publish Branch" and then I click on "origin" right?

2020-05-11 02:10 UTC, mtreacy002 commented
> Just to make sure, once I commited it, I click on "Publish Branch" and then I click on "origin" right?

You meant `push too...` then choose `origin`? Yes, that's right.

<img width="283" alt="Screen Shot 2020-05-11 at 12 09 52 pm" src="https://user-images.githubusercontent.com/29667122/81518129-5cc91380-9380-11ea-8c36-c6a0bb98dfeb.png">
<img width="302" alt="Screen Shot 2020-05-11 at 12 10 00 pm" src="https://user-images.githubusercontent.com/29667122/81518137-65b9e500-9380-11ea-86ee-ba16fb8e10d7.png">

2020-05-11 02:21 UTC, Menina294 commented
Okay, just pushed it! Now what do I do next? I just want to double check.

2020-05-11 02:25 UTC, mtreacy002 submitted a review, later dismissed
Well done, @Menina294. Now we just to wait for another reviewer to approve this change as well. I've already requested @isabelcosta to give her review. Thanks again for your contribution.

2020-05-11 11:49 UTC, isabelcosta requested changes
@Menina294 this PR is almost done :)
There is just one little change left, your README is inside `.github` folder, when it should be in the root folder of this repository (the folder that contains the `.github` folder). Can you move it to the root folder of the repository?

2020-05-14 05:22 UTC, Menina294 commented
Sorry for not responding sooner! I've been having a lot of internet and notification issues from my side. It's pretty late for me right now so I will try to make @isabelcosta 's suggested changes tommorow. Again, sorry!

2020-05-14 19:22 UTC, Menina294 commented
So to move the README file @isabelcosta, do I simply have to go into my folders and move it there? Or is there an easier way in VSCode?

2020-05-17 12:30 UTC, isabelcosta commented
@Menina294 you can simply move the file on folders or drag and drop on VScode :) you are almost done with this 👏 💪 just move it, commit and push and I am more than happy to approve this 😄

2020-05-18 22:45 UTC, Menina294 commented
So I have a feeling I may have messed it up again. I believe that I pushed it first and then commited it. Should I push it again?

Also, I moved the file by using ctrl X and ctrl V, but now it shows two README files. Should I simply commit it again and get rid of the file in the .github folder?

![image](https://user-images.githubusercontent.com/58502374/82266298-3118d100-991e-11ea-87c0-adb8298092f4.png)
![image](https://user-images.githubusercontent.com/58502374/82266323-3ece5680-991e-11ea-9bca-fad1aec28eae.png)

2020-05-19 16:22 UTC, isabelcosta commented
@Menina294 as per your images, the README appears to be already in the right place :) so now you have to commit and push the change :D

2020-05-20 20:49 UTC, Menina294 commented
I believe I pushed it, but just to double check, I was to push to my `origin` branch or my `upstream` branch?

2020-05-30 15:29 UTC, isabelcosta commented
@Menina294 you can push to `origin` :) that will update automatically this PR

2020-05-31 17:56 UTC, meenakshi-dhanani commented
@isabelcosta I see the README has been moved outside .github. Could you re-review?

2020-05-31 18:02 UTC, isabelcosta requested changes
@Menina294 you are almost done ;) Can you remove/delete the extra README you have under `.github`? You have 2 READMEs at the moment, one in the right place (root folder) and another in `.github` folder.

2020-06-01 19:34 UTC, Menina294 commented
Sorry for the late response @isabelcosta! I was unsure at first as to if it was okay to delate it because I used cut/copy to make the README outside that github folder and for soem reason it still stayed in there.

2020-06-01 19:52 UTC, isabelcosta approved these changes
I think it's all good now :) Great work @menina294! Thank you for your contribution👏🏾🎉

2020-06-01 22:43 UTC, Menina294 commented
Oh my lord thanks @isabelcosta for helping me out with this, even though this took a lot longer that it should have 😅, and thanks to @mtreacy002 for helping me figure out the basics of GitHub. 🎉

2020-06-01 23:08 UTC, isabelcosta commented
@Menina294 you are welcome :D You did amazing! You were very very patient which is critical when doing open source contributions. I am super happy we were part of your learning journey 🤗

2020-06-01 23:52 UTC, mtreacy002 approved these changes
This looks good, @Menina294. Thanks soo much for your contribution. 🎉

2020-06-02 04:41 UTC, merged

2020-06-02 04:44 UTC, meenakshi-dhanani commented
Really appreciate your efforts @Menina294 ! Thank you :)